transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -3,14 +3,14 @@
 
 if [ $# -lt 4 ]
 then
-echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-exit 1
+    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
 # assigning parameters to variables
 
-path_to_files=$1
-ip=#$2
+path_to_file=$1
+ip=$2
 username=$3
 path_to_ssh_key=$4
 
@@ -21,7 +21,8 @@ scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$userna
 # checking if file transfer was succesful
  if [ $? -eq 0 ]
  then
- echo "FILE WAS TRANSFERRED SUCCESFULLY"
+     echo "FILE WAS TRANSFERRED SUCCESFULLY"
  else
- echo "FILE TRANSFER FAILED"
+     echo "FILE TRANSFER FAILED"
  fi
+ 
