transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -19,10 +19,9 @@ path_to_ssh_key=$4
 scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:-/"
 
 # checking if file transfer was succesful
- if [ $? -eq 0 ]
- then
-     echo "FILE WAS TRANSFERRED SUCCESFULLY"
- else
-     echo "FILE TRANSFER FAILED"
- fi
- 
+if [ $? -eq 0 ]
+then
+   echo "FILE WAS TRANSFERRED SUCCESFULLY"
+else
+   echo "FILE TRANSFER FAILED"
+fi
